server:
  port: 8079
dubbo:
  application:
    name: consumer
  registry:
    address: nacos地址
  protocol:
    serialization: kryo
nacos:
  config:
    server-addr: nacos地址

logging:
  config: classpath:logging.xml
spring:
  datasource:
    url: jdbc:mysql://mysql地址:3306/r_mall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: 123456
    hikari:
      auto-commit: true
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      maximum-pool-size: 15
      minimum-idle: 5
      pool-name: HikariCP

  jackson:
    default-property-inclusion: non_null
  data:
    mongodb:
      uri: mongodb://mongodb 地址
      password: mongodb 密码
      database: 库名
      username: mongodb 用户名
